version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/project/Assignment3
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python -m unittest -v

workflows:
  version: 2
  build_and_test:
    jobs:
      - test